language: bash
services: docker

env:
  global:
    - DOCKER_VERSION=1.10.1-0~trusty
    - DOCKER_COMPOSE_VERSION=1.6.0

before_install:
  # list docker-engine versions
  - apt-cache madison docker-engine

  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  - curl -s https://raw.githubusercontent.com/ZZROTDesign/docker-clean/master/docker-clean | sudo tee /usr/local/bin/docker-clean > /dev/null && \ sudo chmod +x /usr/local/bin/docker-clean

  # Bats installation
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

  - sudo apt-get install tree


  #- curl -s https://raw.githubusercontent.com/ZZROTDesign/docker-clean/master/docker-clean |
  #- sudo tee /usr/local/bin/docker-clean > /dev/null && \
  #- sudo chmod +x /usr/local/bin/docker-clean

# Install for Shunit
#before_script:
#  - curl -: "https://shunit2.googlecode.com/files/shunit2-2.1.6.tgx" | tar zx
before_script:
  - tree /

script:
  - bats tests/localBatsTests.sh
